from __future__ import annotations

from pathlib import Path
from typing import Callable, Iterable, Optional, Sequence, Tuple, Union

import numpy as np
import scipy.sparse as sp
import torch
from torch import Tensor, nn
import torch.nn.functional as F

try:
    from torch_geometric.data import Data
    from torch_geometric.utils import from_scipy_sparse_matrix
except ImportError:  # pragma: no cover - used only when PyG is absent.
    Data = None
    from_scipy_sparse_matrix = None

from graph_loader import adjacency, biadjacency, load_bipartite_graph, matrix_to_graph
from spectral import g, h, phi, spectral_design_full, spectral_design_trunc


SparseMatrix = Union[sp.spmatrix, np.ndarray]
Activation = Optional[Callable[[Tensor], Tensor]]


def _canonical_mask(mask: SparseMatrix) -> sp.csr_matrix:
    """Return a binary CSR mask with sorted indices."""
    if sp.issparse(mask):
        mask_csr = mask.tocsr(copy=True)
    else:
        mask_csr = sp.csr_matrix(mask)

    mask_csr.sum_duplicates()
    mask_csr.sort_indices()
    if mask_csr.nnz > 0:
        mask_csr.data = np.ones_like(mask_csr.data, dtype=np.float32)
    return mask_csr.astype(np.float32)


def scipy_sparse_to_edge_index(mask: SparseMatrix) -> Tuple[Tensor, Tensor]:
    """Convert a SciPy sparse matrix into PyG-style COO tensors.

    When PyG is installed, this uses the official
    `torch_geometric.utils.from_scipy_sparse_matrix` conversion. Otherwise,
    it falls back to the equivalent manual conversion so the rest of the code
    remains testable in environments without PyG.
    """
    mask_csr = _canonical_mask(mask)
    if from_scipy_sparse_matrix is not None:
        edge_index, edge_weight = from_scipy_sparse_matrix(mask_csr)
        return edge_index.long(), edge_weight.to(torch.float32)

    mask_coo = mask_csr.tocoo()
    edge_index = torch.from_numpy(
        np.vstack([mask_coo.row, mask_coo.col]).astype(np.int64)
    )
    edge_weight = torch.from_numpy(mask_coo.data.astype(np.float32))
    return edge_index, edge_weight


def sparse2vec_from_mask(
    supports: Sequence[SparseMatrix],
    mask: SparseMatrix,
) -> torch.Tensor:
    """Vectorize masked support matrices into edge features C0 in R^{m x S}.

    The row order matches the COO order of `mask`, which is the same order used
    by `scipy_sparse_to_edge_index(mask)`.
    """
    mask_csr = _canonical_mask(mask)
    mask_coo = mask_csr.tocoo()
    rows, cols = mask_coo.row, mask_coo.col

    features = []
    for support in supports:
        support_csr = sp.csr_matrix(support)
        values = np.asarray(support_csr[rows, cols], dtype=np.float32).reshape(-1)
        features.append(values)

    if not features:
        return torch.empty((mask_coo.nnz, 0), dtype=torch.float32)

    stacked = np.stack(features, axis=1).astype(np.float32, copy=False)
    return torch.from_numpy(stacked)


def build_receptive_field_mask(
    G,
    include_self_loops: bool = True,
) -> sp.csr_matrix:
    """Build the 1-hop receptive field mask M used in the paper.

    The paper uses M = A + I for the experiments. `graph_loader.adjacency(G)`
    already returns the full homogeneous adjacency of the bipartite graph with
    node ordering [users..., items...].
    """
    A = adjacency(G).tocsr().astype(np.float32)
    if include_self_loops:
        A = A + sp.eye(A.shape[0], dtype=np.float32, format="csr")
    return _canonical_mask(A)


def precompute_gnnml3_edge_features(
    G,
    num_supports: int,
    mask: Optional[SparseMatrix] = None,
    spectral_mode: str = "full",
    trunc_rank: Optional[int] = None,
    include_identity_support: bool = True,
) -> Tuple[torch.Tensor, torch.Tensor, sp.csr_matrix]:
    """Precompute the fixed spectral edge features used by GNNML3.

    Parameters
    ----------
    G:
        A NetworkX graph compatible with `graph_loader.py` and `spectral.py`.
    num_supports:
        Total number of supports expected by the model. If
        `include_identity_support=True`, one column is reserved for the all-pass
        identity support and the remaining columns are generated by `spectral.py`.
    mask:
        Sparse receptive field mask M. Defaults to A + I.
    spectral_mode:
        Either "full" or "trunc".
    trunc_rank:
        Required only when `spectral_mode="trunc"`.

    Returns
    -------
    edge_index:
        PyG-style edge indices describing the receptive field mask.
    edge_attr:
        Initial edge features C0 aligned with `edge_index`, shape [num_edges, S].
    mask:
        The canonical CSR receptive field mask.
    """
    if num_supports <= 0:
        raise ValueError("num_supports must be positive")

    mask_csr = build_receptive_field_mask(G) if mask is None else _canonical_mask(mask)
    total_supports = num_supports
    spectral_supports_needed = total_supports - int(include_identity_support)

    supports = []
    if include_identity_support:
        supports.append(sp.eye(mask_csr.shape[0], dtype=np.float32, format="csr"))

    if spectral_supports_needed > 0:
        if spectral_mode == "full":
            spectral_supports = spectral_design_full(
                G,
                mask_csr,
                spectral_supports_needed,
                phi,
                h,
                g,
            )
        elif spectral_mode == "trunc":
            if trunc_rank is None:
                raise ValueError("trunc_rank must be provided when spectral_mode='trunc'")
            spectral_supports = spectral_design_trunc(
                G,
                mask_csr,
                spectral_supports_needed,
                trunc_rank,
                phi,
                h,
                g,
            )
        else:
            raise ValueError("spectral_mode must be either 'full' or 'trunc'")
        supports.extend(sp.csr_matrix(support) for support in spectral_supports)

    edge_index, _ = scipy_sparse_to_edge_index(mask_csr)
    edge_attr = sparse2vec_from_mask(supports, mask_csr)
    return edge_index, edge_attr, mask_csr


def build_pyg_data_from_graph(
    G,
    x: Optional[Union[Tensor, np.ndarray, Tuple[Union[Tensor, np.ndarray], Union[Tensor, np.ndarray]]]] = None,
    num_supports: int = 4,
    mask: Optional[SparseMatrix] = None,
    spectral_mode: str = "full",
    trunc_rank: Optional[int] = None,
    include_identity_support: bool = True,
):
    """Create a PyG `Data` object whose edge_attr are GNNML3 spectral features.

    `x` can either be:
      * a full node feature matrix of shape [num_nodes, num_features], or
      * a tuple `(x_users, x_items)` which will be concatenated in the node order
        used by `graph_loader.adjacency`.
    """
    if Data is None:
        raise ImportError("torch_geometric is required to build a PyG Data object")

    B = biadjacency(G)
    num_users, num_items = B.shape
    num_nodes = num_users + num_items

    if x is None:
        x_tensor = torch.ones((num_nodes, 1), dtype=torch.float32)
    elif isinstance(x, tuple):
        x_user, x_item = x
        x_user = torch.as_tensor(x_user, dtype=torch.float32)
        x_item = torch.as_tensor(x_item, dtype=torch.float32)
        x_tensor = torch.cat([x_user, x_item], dim=0)
    else:
        x_tensor = torch.as_tensor(x, dtype=torch.float32)

    if x_tensor.size(0) != num_nodes:
        raise ValueError(
            f"Expected {num_nodes} node features in graph order [users..., items...], "
            f"but got {x_tensor.size(0)}"
        )

    edge_index, edge_attr, mask_csr = precompute_gnnml3_edge_features(
        G=G,
        num_supports=num_supports,
        mask=mask,
        spectral_mode=spectral_mode,
        trunc_rank=trunc_rank,
        include_identity_support=include_identity_support,
    )

    data = Data(x=x_tensor, edge_index=edge_index, edge_attr=edge_attr)
    data.num_nodes = num_nodes
    data.num_users = num_users
    data.num_items = num_items
    data.receptive_field_nnz = int(mask_csr.nnz)
    return data


def build_pyg_data_from_txt(
    txt_path: Union[str, Path],
    x: Optional[Union[Tensor, np.ndarray, Tuple[Union[Tensor, np.ndarray], Union[Tensor, np.ndarray]]]] = None,
    num_supports: int = 4,
    mask: Optional[SparseMatrix] = None,
    spectral_mode: str = "full",
    trunc_rank: Optional[int] = None,
    include_identity_support: bool = True,
):
    """Load a graph with `graph_loader.py` and convert it into a PyG `Data`."""
    G = load_bipartite_graph(txt_path)
    return build_pyg_data_from_graph(
        G=G,
        x=x,
        num_supports=num_supports,
        mask=mask,
        spectral_mode=spectral_mode,
        trunc_rank=trunc_rank,
        include_identity_support=include_identity_support,
    )


def build_pyg_data_from_biadjacency(
    B: sp.csr_matrix,
    x: Optional[Union[Tensor, np.ndarray, Tuple[Union[Tensor, np.ndarray], Union[Tensor, np.ndarray]]]] = None,
    num_supports: int = 4,
    mask: Optional[SparseMatrix] = None,
    spectral_mode: str = "full",
    trunc_rank: Optional[int] = None,
    include_identity_support: bool = True,
):
    """Convenience wrapper for in-memory bipartite matrices."""
    G = matrix_to_graph(B)
    return build_pyg_data_from_graph(
        G=G,
        x=x,
        num_supports=num_supports,
        mask=mask,
        spectral_mode=spectral_mode,
        trunc_rank=trunc_rank,
        include_identity_support=include_identity_support,
    )


class GNNML3Layer(nn.Module):
    """One GNNML3 layer implementing Eq. (6) from the paper.

    This layer expects the *fixed* spectral edge features C0 (called C' in the
    paper) and recomputes the learned sparse supports at every layer from those
    fixed features, matching Algorithm 2.
    """

    def __init__(
        self,
        in_channels: int,
        conv_out_channels: int,
        num_supports: int,
        product_out_channels: Optional[int] = None,
        activation: Activation = F.relu,
    ) -> None:
        super().__init__()
        if num_supports <= 0:
            raise ValueError("num_supports must be positive")
        if in_channels <= 0 or conv_out_channels <= 0:
            raise ValueError("channel dimensions must be positive")

        self.in_channels = in_channels
        self.conv_out_channels = conv_out_channels
        self.num_supports = num_supports
        self.product_out_channels = product_out_channels or conv_out_channels
        self.activation = activation

        self.mlp1 = nn.Sequential(nn.Linear(num_supports, 2 * num_supports), nn.Sigmoid())
        self.mlp2 = nn.Sequential(nn.Linear(num_supports, 2 * num_supports), nn.Sigmoid())
        self.mlp3 = nn.Sequential(nn.Linear(num_supports, 2 * num_supports), nn.Sigmoid())
        self.mlp4 = nn.Sequential(nn.Linear(4 * num_supports, num_supports), nn.ReLU())

        self.support_linears = nn.ModuleList(
            nn.Linear(in_channels, conv_out_channels, bias=False)
            for _ in range(num_supports)
        )
        self.mlp5 = nn.Linear(in_channels, self.product_out_channels)
        self.mlp6 = nn.Linear(in_channels, self.product_out_channels)

        self.reset_parameters()

    def reset_parameters(self) -> None:
        for mlp in (self.mlp1, self.mlp2, self.mlp3, self.mlp4):
            for module in mlp:
                if isinstance(module, nn.Linear):
                    nn.init.xavier_uniform_(module.weight)
                    if module.bias is not None:
                        nn.init.zeros_(module.bias)

        for linear in self.support_linears:
            nn.init.xavier_uniform_(linear.weight)

        nn.init.xavier_uniform_(self.mlp5.weight)
        nn.init.zeros_(self.mlp5.bias)
        nn.init.xavier_uniform_(self.mlp6.weight)
        nn.init.zeros_(self.mlp6.bias)

    def learn_support_edge_weights(self, c0: Tensor) -> Tensor:
        """Learn support weights C from fixed spectral features C0."""
        if c0.dim() != 2 or c0.size(-1) != self.num_supports:
            raise ValueError(
                f"Expected c0 with shape [num_edges, {self.num_supports}], got {tuple(c0.shape)}"
            )
        a = self.mlp1(c0)
        b = self.mlp2(c0)
        c = self.mlp3(c0)
        return self.mlp4(torch.cat([a, b * c], dim=-1))

    @staticmethod
    def _support_tensor(edge_index: Tensor, edge_weight: Tensor, num_nodes: int) -> Tensor:
        support = torch.sparse_coo_tensor(
            edge_index,
            edge_weight,
            size=(num_nodes, num_nodes),
            device=edge_weight.device,
        )
        return support.coalesce()

    def forward(
        self,
        x: Tensor,
        edge_index: Tensor,
        c0: Tensor,
        num_nodes: Optional[int] = None,
    ) -> Tensor:
        if x.dim() != 2:
            raise ValueError(f"Expected x to have shape [num_nodes, num_features], got {tuple(x.shape)}")
        if edge_index.dim() != 2 or edge_index.size(0) != 2:
            raise ValueError(f"Expected edge_index with shape [2, num_edges], got {tuple(edge_index.shape)}")

        num_nodes = int(num_nodes if num_nodes is not None else x.size(0))
        edge_index = edge_index.to(device=x.device, dtype=torch.long)
        c0 = c0.to(device=x.device, dtype=x.dtype)

        learned_edge_weights = self.learn_support_edge_weights(c0)

        conv_out = x.new_zeros((num_nodes, self.conv_out_channels))
        for support_id, linear in enumerate(self.support_linears):
            transformed_x = linear(x)
            support = self._support_tensor(edge_index, learned_edge_weights[:, support_id], num_nodes)
            conv_out = conv_out + torch.sparse.mm(support, transformed_x)

        product_out = self.mlp5(x) * self.mlp6(x)
        out = torch.cat([conv_out, product_out], dim=-1)
        if self.activation is not None:
            out = self.activation(out)
        return out


class GNNML3(nn.Module):
    """Stacked GNNML3 encoder for PyTorch/PyG workflows.

    The model consumes PyG-style inputs `(x, edge_index, edge_attr)` where
    `edge_attr` stores the fixed spectral edge features C0. Since Algorithm 2
    recomputes the learned supports from the same C0 at every layer, the same
    `edge_attr` is reused across all layers.
    """

    def __init__(
        self,
        in_channels: int,
        hidden_channels: Union[int, Sequence[int]],
        num_supports: int,
        num_layers: Optional[int] = None,
        product_channels: Optional[Union[int, Sequence[int]]] = None,
        dropout: float = 0.0,
        activation: Activation = F.relu,
    ) -> None:
        super().__init__()
        if isinstance(hidden_channels, int):
            if num_layers is None:
                raise ValueError("num_layers must be provided when hidden_channels is an int")
            conv_dims = [hidden_channels] * num_layers
        else:
            conv_dims = list(hidden_channels)
            if not conv_dims:
                raise ValueError("hidden_channels sequence must not be empty")
            if num_layers is not None and num_layers != len(conv_dims):
                raise ValueError("num_layers does not match len(hidden_channels)")

        if product_channels is None:
            prod_dims = conv_dims
        elif isinstance(product_channels, int):
            prod_dims = [product_channels] * len(conv_dims)
        else:
            prod_dims = list(product_channels)
            if len(prod_dims) != len(conv_dims):
                raise ValueError("product_channels must have the same length as hidden_channels")

        self.dropout = float(dropout)
        self.layers = nn.ModuleList()

        current_in = in_channels
        for conv_dim, prod_dim in zip(conv_dims, prod_dims):
            layer = GNNML3Layer(
                in_channels=current_in,
                conv_out_channels=conv_dim,
                num_supports=num_supports,
                product_out_channels=prod_dim,
                activation=activation,
            )
            self.layers.append(layer)
            current_in = conv_dim + prod_dim

        self.out_channels = current_in

    def forward(
        self,
        data_or_x,
        edge_index: Optional[Tensor] = None,
        edge_attr: Optional[Tensor] = None,
    ) -> Tensor:
        if edge_index is None:
            if not hasattr(data_or_x, "x") or not hasattr(data_or_x, "edge_index"):
                raise ValueError("Pass either a PyG data object or explicit (x, edge_index, edge_attr)")
            x = data_or_x.x
            edge_index = data_or_x.edge_index
            if edge_attr is None:
                if hasattr(data_or_x, "edge_attr") and data_or_x.edge_attr is not None:
                    edge_attr = data_or_x.edge_attr
                elif hasattr(data_or_x, "c0"):
                    edge_attr = data_or_x.c0
                else:
                    raise ValueError("No spectral edge features found. Expected data.edge_attr or data.c0")
        else:
            x = data_or_x
            if edge_attr is None:
                raise ValueError("edge_attr must be provided when calling forward(x, edge_index, edge_attr)")

        for layer_id, layer in enumerate(self.layers):
            x = layer(x, edge_index=edge_index, c0=edge_attr)
            if self.dropout > 0.0 and layer_id + 1 < len(self.layers):
                x = F.dropout(x, p=self.dropout, training=self.training)
        return x


__all__ = [
    "GNNML3",
    "GNNML3Layer",
    "build_pyg_data_from_biadjacency",
    "build_pyg_data_from_graph",
    "build_pyg_data_from_txt",
    "build_receptive_field_mask",
    "precompute_gnnml3_edge_features",
    "scipy_sparse_to_edge_index",
    "sparse2vec_from_mask",
]
